notifyBot:
  token: "YOUR_BOT_1_TOKEN"
  chat_id: "YOUR_BOT_1_CHAT_ID"

controlBot:
  token: "YOUR_BOT_2_TOKEN"
  chat_id: "YOUR_BOT_2_CHAT_ID"

server:
  ip: play.minechoseland.my.id
  port: 19132

log:
  chat: true
  join: true
  quit: true
  death: true
  mining: true

block_notify_filter:
  ANCIENT_DEBRIS: true
  COAL_ORE: true
  COPPER_ORE: true
  DEEPSLATE_COAL_ORE: true
  DEEPSLATE_COPPER_ORE: true
  DEEPSLATE_DIAMOND_ORE: true
  DEEPSLATE_EMERALD_ORE: true
  DEEPSLATE_GOLD_ORE: true
  DEEPSLATE_IRON_ORE: true
  DEEPSLATE_LAPIS_ORE: true
  DEEPSLATE_REDSTONE_ORE: true
  DIAMOND_ORE: true
  EMERALD_ORE: true
  GOLD_ORE: true
  IRON_ORE: true
  LAPIS_ORE: true
  NETHER_GOLD_ORE: true
  NETHER_QUARTZ_ORE: true
  RAW_COPPER: true
  RAW_GOLD: true
  RAW_IRON: true
  REDSTONE_ORE: true

count_block_destroy_xray:
  ANCIENT_DEBRIS: 64
  COAL_ORE: 64
  COPPER_ORE: 64
  DEEPSLATE_COAL_ORE: 64
  DEEPSLATE_COPPER_ORE: 64
  DEEPSLATE_DIAMOND_ORE: 64
  DEEPSLATE_EMERALD_ORE: 64
  DEEPSLATE_GOLD_ORE: 64
  DEEPSLATE_IRON_ORE: 64
  DEEPSLATE_LAPIS_ORE: 64
  DEEPSLATE_REDSTONE_ORE: 64
  DIAMOND_ORE: 64
  EMERALD_ORE: 64
  GOLD_ORE: 64
  IRON_ORE: 64
  LAPIS_ORE: 64
  NETHER_GOLD_ORE: 64
  NETHER_QUARTZ_ORE: 64
  RAW_COPPER: 64
  RAW_GOLD: 64
  RAW_IRON: 64
  REDSTONE_ORE: 64
