name: Build Plugin

on:
  push:
    branches:
      - With_Filter_Deepseek
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Plugin Jar
      uses: actions/upload-artifact@v3
      with:
        name: TeleChatSRV
        path: build/libs/*.jar
